"""create analyses table

Revision ID: f162e9ca2271
Revises: 621640a0a845
Create Date: 2026-07-04 02:43:33.878904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f162e9ca2271'
down_revision: Union[str, Sequence[str], None] = '621640a0a845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('research_result', sa.JSON(), nullable=True),
    sa.Column('market_result', sa.JSON(), nullable=True),
    sa.Column('competitor_result', sa.JSON(), nullable=True),
    sa.Column('risk_result', sa.JSON(), nullable=True),
    sa.Column('final_decision', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyses')
    # ### end Alembic commands ###
